### ISSUE TITLE
question about tone mapping

### ISSUE THREAD

**Issue by HuTaoMylove** [Hans1984/CineGS#1]
Thank you for your nice work! I'm confused about the tone mapping function .Why aperture is used in equal 7 but I could not find aperture  in your code?

**Comment by HuTaoMylove** [comment]
![image](https://github.com/user-attachments/assets/1e097db4-29a8-4386-aa8f-1c8beac983ca)

**Comment by HuTaoMylove** [comment]
![image](https://github.com/user-attachments/assets/89ce9990-bdf7-4266-9cd1-c47825500277)

**Comment by Hans1984** [comment]
Thank you for your interest in our work. We have precomputed the exposure values for time and aperture in advance. The time parameter here will directly load the exposure values.

**Comment by HuTaoMylove** [comment]
Thank you for your reply!I want to use your code in real world capture imgs and could get time and aperture from exif.So I just need to calculate tone mapping func as you write in your paper,right? Is there any preprocessing needed?   tks!

**Comment by Hans1984** [comment]
You are welcome. I only precomputed the exposure values for our dataset. If you need to test your dataset, you also need to precompute them in advance.
